### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by 1YwY1** [qlt315/Blockchain-enabled-UCMEC#3]
Thank you very much,I want to run the"Impact Parameters of Sb ",what is the " IP_Sb_energy_list"

**Comment by qlt315** [comment]
inv_ pos is the expression representing the reciprocal in CVX. Please ensure that you have installed CVX before running the code.

**Comment by 1YwY1** [comment]
> inv_ pos is the expression representing the reciprocal in CVX. Please ensure that you have installed CVX before running the code.谢谢，这个问题我已经解决了，还有另外一个问题就是我想跑"Impact Parameters of Sb "这一部分，但是我没有找到 'IP_Sb_energy_list'这个定义在哪了。
Thank you. I have already solved this problem. There is another problem that I want to run the "Impact Parameters of Sb "section, but I can't find the definition 'IP_Sb_energy_list'

**Comment by qlt315** [comment]
I have uploaded the raw data of the experiment to the “data” folder of this repository. You can import these data to plot the figure you want.
