### ISSUE TITLE
是否缺失了impact_parameters_Sb.m

### ISSUE THREAD

**Issue by wkyd** [qlt315/Blockchain-enabled-UCMEC#5]

**Comment by qlt315** [comment]
同学你好！应该没有缺失。目前这个库应该需要手动修改参数。

**Comment by wkyd** [comment]
> 同学你好！应该没有缺失。目前这个库应该需要手动修改参数。

您好，求教一下：请问我在执行完Figure_generation.m后，提示”
>> Figure_generation
未定义函数或变量 'convergence_AP_list'。

出错 Figure_generation (line 4)
x_AP_3 = convergence_AP_list(1,:);“，这种情况是怎么回事，该怎么处理。

**Comment by wkyd** [comment]
> 同学你好！应该没有缺失。目前这个库应该需要手动修改参数。

抱歉再次求教，请问这几个matlab脚本的执行顺序是什么。

**Comment by wkyd** [comment]
> 同学你好！应该没有缺失。目前这个库应该需要手动修改参数。

您好，我在使用matlab打开文件后，出现“angle=rand(1,M)*2*pi; %(0,2*pi)涔嬮棿鍧囧寑鍒嗗竷鏁版嵁鐐� 
r=200*sqrt(rand(1,M)); %锛�0,1锛変箣闂磖^2鍧囧寑鍒嗗竷鏁版嵁鐐�
x_ap=r.*cos(angle); %AP鐨剎鍧愭爣
y_ap=r.*sin(angle); %AP鐨剏鍧愭爣

angle_1=rand(1,N)*2*pi; %(0,2*pi)涔嬮棿鍧囧寑鍒嗗竷鏁版嵁鐐� 
r_1=200*sqrt(rand(1,N)); %锛�0,1锛変箣闂磖^2鍧囧寑鍒嗗竷鏁版嵁鐐�”这样的字体，抱歉请问您知道这是怎么回事吗?

**Comment by wkyd** [comment]
> 同学你好！应该没有缺失。目前这个库应该需要手动修改参数。

抱歉我不知道该如何修改参数，抱歉请问您可以给点指点吗？

**Comment by qlt315** [comment]
同学你好：
（1）关于变量未定义的问题，你需要先导入data文件夹下的变量再进行绘图。
（2）关于Matlab中文注释乱码的问题，有可能是因为你Matlab版本过低导致的，建议下载最新版本的Matlab，此外这个问题也可以参照网上的问题教程进行解决。我目前用的Matlab R2024b下注释是正常显示的。
（3）关于脚本执行顺序的问题，几个main函数是不同算法的主程序，其他的有绘制收敛图的，有看不同用户数下时延能耗的，具体可参照文件里的注释。
（4）关于参数修改的问题，可以先阅读理解代码之后，看你想更改系统中的哪个参数，之后自行进行修改即可。

**Comment by wkyd** [comment]
非常感谢您的指点，我马上进行实践。再次感谢！



---原始邮件---
发件人: "Langtian ***@***.***&gt;
发送时间: 2024年10月28日(周一) 中午11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [qlt315/Blockchain-enabled-UCMEC] 是否缺失了impact_parameters_Sb.m (Issue #5)




 
同学你好：
 （1）关于变量未定义的问题，你需要先导入data文件夹下的变量再进行绘图。
 （2）关于Matlab中文注释乱码的问题，有可能是因为你Matlab版本过低导致的，建议下载最新版本的Matlab，此外这个问题也可以参照网上的问题教程进行解决。我目前用的Matlab R2024b下注释是正常显示的。
 （3）关于脚本执行顺序的问题，几个main函数是不同算法的主程序，其他的有绘制收敛图的，有看不同用户数下时延能耗的，具体可参照文件里的注释。
 （4）关于参数修改的问题，可以先阅读理解代码之后，看你想更改系统中的哪个参数，之后自行进行修改即可。

**Comment by wkyd** [comment]
> 同学你好： （1）关于变量未定义的问题，你需要先导入data文件夹下的变量再进行绘图。 （2）关于Matlab中文注释乱码的问题，有可能是因为你Matlab版本过低导致的，建议下载最新版本的Matlab，此外这个问题也可以参照网上的问题教程进行解决。我目前用的Matlab R2024b下注释是正常显示的。 （3）关于脚本执行顺序的问题，几个main函数是不同算法的主程序，其他的有绘制收敛图的，有看不同用户数下时延能耗的，具体可参照文件里的注释。 （4）关于参数修改的问题，可以先阅读理解代码之后，看你想更改系统中的哪个参数，之后自行进行修改即可。

请问您用的哪个版本的cvx?谢谢。

**Comment by qlt315** [comment]
应该是cvx3.0
